providers = ["node", "python"]

[phases.install]
cmds = [
  "cd simulador/frontend && npm install && cd ../..",
  "python -m pip install --user -r simulador/requirements.txt"
]

[phases.build]
cmds = ["cd simulador/frontend && npm run build && cd ../.."]

[start]
cmd = "cd simulador && python3 colab_server.py"
