[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "cd simulador/frontend && npm install && cd ../..",
  "pip3 install -r simulador/requirements.txt"
]

[phases.build]
cmds = ["cd simulador/frontend && npm run build && cd ../.."]

[start]
cmd = "cd simulador && python3 colab_server.py"
